### ISSUE TITLE
Crash with a weird Error Message 1.18 Bug Fabric

### ISSUE THREAD

**Issue by AkariuTamokiy** [franiscoder/dark-enchanting#60]
Hello,
Since I put up an Dark Enchantment Table and used it to disenchant to recieve exp I had theses issues. I crash with that error:

java.lang.NullPointerExceptionCannot invoke "java.lang.Integer.intValue()" because "$$1" is null

and the server gives me this:
```
[17.06 13:10:40] [Server] [Server thread/INFO]: AkariuTamokiy joined the game
[17.06 13:10:40] [Multicraft] AkariuTamokiy ran command Message of the Day
[17.06 13:10:40] [Server] [Netty Epoll Server IO #48/INFO]: Priority overwritten for player . Normal: GRAVE / Robbing: INVENTORY
[17.06 13:10:40] [Server] [Netty Epoll Server IO #48/ERROR]: Error receiving packet 77
[17.06 13:10:40] [Server] java.lang.NullPointerExceptionCannot invoke "java.lang.Integer.intValue()" because "$$1" is null
[17.06 13:10:40] [Server] 	at net.minecraft.class_2943$12.method_12766(class_2943.java:47) ~[server-intermediary.jar:?]
[17.06 13:10:40] [Server] 	at net.minecraft.class_2943$12.method_12715(class_2943.java:44) ~[server-intermediary.jar:?]
[17.06 13:10:40] [Server] 	at net.minecraft.class_2945.method_12782(class_2945.java:195) ~[server-intermediary.jar:?]
[17.06 13:10:40] [Server] 	at net.minecraft.class_2945.method_12787(class_2945.java:140) ~[server-intermediary.jar:?]
[17.06 13:10:40] [Server] 	at net.minecraft.class_2739.method_11052(class_2739.java:34) ~[server-intermediary.jar:?]
[17.06 13:10:40] [Server] 	at net.minecraft.class_2545.method_10838(class_2545.java:45) [server-intermediary.jar:?]
[17.06 13:10:40] [Server] 	at net.minecraft.class_2545.encode(class_2545.java:14) [server-intermediary.jar:?]
[17.06 13:10:40] [Server] 	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107) [netty-all-4.1.68.Final.jar:?]
[17.06 13:10:40] [Server] 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) [netty-all-4.1.68.Final.jar:?]
[17.06 13:10:40] [Server] 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709) [netty-all-4.1.68.Final.jar:?]
[17.06 13:10:40] [Server] 	at io.netty.channel.AbstractChannelHandlerContext$WriteTask.run(AbstractChannelHandlerContext.java:1069) [netty-all-4.1.68.Final.jar:?]
[17.06 13:10:40] [Server] 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) [netty-all-4.1.68.Final.jar:?]
[17.06 13:10:40] [Server] 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469) [netty-all-4.1.68.Final.jar:?]
[17.06 13:10:40] [Server] 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:387) [netty-all-4.1.68.Final.jar:?]
[17.06 13:10:40] [Server] 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) [netty-all-4.1.68.Final.jar:?]
[17.06 13:10:40] [Server] 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-all-4.1.68.Final.jar:?]
[17.06 13:10:40] [Server] 	at java.lang.Thread.run(Thread.java:833) [?:?]
[17.06 13:10:41] [Disconnect] AkariuTamokiy has disconnected, reasonInternal Exception: io.netty.handler.codec.EncoderException: java.lang.NullPointerException: Cannot invoke "java.lang.Integer.intValue()" because "$$1" is null
[17.06 13:10:41] [Server] [Server thread/INFO]: AkariuTamokiy left the game
```

Last time I fixed it by deleting all my inventory items while I join the server to delete the items I already disenchanted because I thought that that would be the culprit and sure it helped but now I got it while enchanting a sword with soulbound and it crashed with the same issues. I don't really know how to trigger it. The only things that help is deleting inventory while joining or delete the playerdata. The mod is included in the Medieval Minecraft modpack what I currently play

**Comment by frqnny** [comment]
I’ve never seen this issue. IDK if it is my mod, but if I can’t reproduce I can’t really fix

**Comment by AkariuTamokiy** [comment]
Like I mentioned it only happend after I used the Dark Enchantment Table so this is the only clue I got that it has to be it.
But is there somewere a local log I can provide besides what the server is giving out?

**Comment by frqnny** [comment]
Can you try taking out the mod and seeing if the issue still occurs?

**Comment by frqnny** [comment]
oops

**Comment by AkariuTamokiy** [comment]
I testetd it now and nothing happend in the almost 2 days. Also it really only happend mostly short after I used the enchanting table when it happend and a friend who playes with me never had these issues because she never used the table in the first place. The only thing I can imagine is that some of the added enchantments through other mods that came with the modpack are the cause in combination with the table or rather the ability to have these enchantments all at the same time active on one item.

**Comment by AkariuTamokiy** [comment]
So the mod is now active on the server for a week and nothing happend but only because we didn't used it since then either.  I'don't know what could cause this issue really. Could be this mod, could be a mod that adds more enchantments....IDK.
