### ISSUE TITLE
"Encountered an unexpected exception" when using mod on server (1.20.1)

### ISSUE THREAD

**Issue by MrMasrozYTLIVE** [franiscoder/dark-enchanting#83]
### **UPD Tutorial how to fix this issue: https://github.com/frqnny/dark-enchanting/issues/83#issuecomment-1891009757**

I use same modpacks on both client and server. When i placed enchanter on a server and tried to use it server crashed with folowing error. On a client it works and didnt crash when i tried to use Dark Enchanted in a SinglePlayer world.

```
java.lang.NoSuchFieldError: backgroundPainter
        at io.github.cottonmc.cotton.gui.widget.WPanel.<init>(WPanel.java:27) ~[libgui-8.0.1+1.20-53e2a69f3f0c7058.jar:?]
        at io.github.cottonmc.cotton.gui.widget.WPanelWithInsets.<init>(WPanelWithInsets.java:12) ~[libgui-8.0.1+1.20-53e2a69f3f0c7058.jar:?]
        at io.github.cottonmc.cotton.gui.widget.WGridPanel.<init>(WGridPanel.java:33) ~[libgui-8.0.1+1.20-53e2a69f3f0c7058.jar:?]
        at io.github.cottonmc.cotton.gui.SyncedGuiDescription.<init>(SyncedGuiDescription.java:53) ~[libgui-8.0.1+1.20-53e2a69f3f0c7058.jar:?]
        at io.github.frqnny.darkenchanting.client.gui.DarkEnchanterGUI.<init>(DarkEnchanterGUI.java:52) ~[dark-enchanting-1.0.3+1.20.1.jar:?]
        at io.github.frqnny.darkenchanting.blockentity.DarkEnchanterBlockEntity.createMenu(DarkEnchanterBlockEntity.java:36) ~[dark-enchanting-1.0.3+1.20.1.jar:?]
        at net.minecraft.class_3222.method_17355(class_3222.java:1034) ~[server-intermediary.jar:?]
        at io.github.frqnny.darkenchanting.block.DarkEnchanterBlock.method_9534(DarkEnchanterBlock.java:53) ~[dark-enchanting-1.0.3+1.20.1.jar:?]
        at net.minecraft.class_4970$class_4971.method_26174(class_4970.java:1133) ~[server-intermediary.jar:?]
        at net.minecraft.class_3225.method_14262(class_3225.java:343) ~[server-intermediary.jar:?]
        at net.minecraft.class_3244.method_12046(class_3244.java:1140) ~[server-intermediary.jar:?]
        at net.minecraft.class_2885.method_12547(class_2885.java:34) ~[server-intermediary.jar:?]
        at net.minecraft.class_2885.method_11054(class_2885.java:8) ~[server-intermediary.jar:?]
        at net.minecraft.class_2600.method_11072(class_2600.java:22) ~[server-intermediary.jar:?]
        at net.minecraft.class_3738.run(class_3738.java:18) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_18859(class_1255.java:156) ~[server-intermediary.jar:?]
        at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:782) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:164) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_16075(class_1255.java:130) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:6818) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:758) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_18857(class_1255.java:139) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:743) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:675) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) ~[server-intermediary.jar:?]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
```

**Comment by MrMasrozYTLIVE** [comment]
I use:
Minecraft 1.20.1
Fabric loader 0.15.3
Dark Enchanting 1.0.3+1.20.1

**Comment by MrMasrozYTLIVE** [comment]
It actually happens due to [this issue](https://github.com/CottonMC/LibGui/issues/234) with LibGui and Fabric Loader 0.15

**Comment by MrMasrozYTLIVE** [comment]
It was fixed with updated LibGUI. I hope you'll update it in your mod too

**Comment by MrMasrozYTLIVE** [comment]
https://github.com/CottonMC/LibGui/releases/tag/8.1.1 this version is required to fix server-side crash

**Comment by Shaccoo46** [comment]
Hello !! 

I had the exact same issue, could not open the dark enchanting table on a server 

How did you update the file ? Like where should i put the new version of LibGUI

**Comment by MrMasrozYTLIVE** [comment]
> Hello !!
> 
> I had the exact same issue, could not open the dark enchanting table on a server
> 
> How did you update the file ? Like where should i put the new version of LibGUI

Hey, its quite easy. You just need to download new LibGUI version, then put it in the mods and do next few steps:
1) Open Dark Enchanting jar as archive (7zip or WinRar or anything else)
2) Open fabric.mod.json
3) Find `  "jars": [` at the end of the json file
4) Remove LibGUI from there (It ships custom LibGUI version so yeah, you need to remove it)
5) Save fabric.mod.json after steps 3 and 4.
6) Put it in mod jar (If you opened it directly from jar it should ask to replace old json with new one)
7) ???
8) Enjoy this mod

**Comment by MrMasrozYTLIVE** [comment]
Or if you know how to compile jars you can compile it yourself from my repo (Fork for Pull Request. I kinda fixed it, but it wont be in the original mod until PR is accepted) https://github.com/MrMasrozYTLIVE/dark-enchanting/tree/patch-1

**Comment by Shaccoo46** [comment]
oooooh okay it's quite easy actually, i didn't do it this way when i tried, i guess it should explain why my server crashed when i tried to launch it with the mod when i modified it myself !! Thanks a lot i'm gonna try :) !

**Comment by MrMasrozYTLIVE** [comment]
> oooooh okay it's quite easy actually, i didn't do it this way when i tried, i guess it should explain why my server crashed when i tried to launch it with the mod when i modified it myself !! Thanks a lot i'm gonna try :) !

Well i didnt really do anything. I just wrote that i have same [issue](https://github.com/CottonMC/LibGui/issues/234) and some dude fixed it and uploaded 8.1.1 LibGUI with this issue fixed. All I did is just change version of LibGui in properties

**Comment by Shaccoo46** [comment]
THANK THE LORD IT WORKS THANKS THANKS

**Comment by MrMasrozYTLIVE** [comment]
Yw lol

**Comment by MrMasrozYTLIVE** [comment]
Its very easy thing to fix so yeah. Its all bcuz of LibGui which is included in the mod. It doesnt really support Fabric Loader 0.15 so either do this thing or use Fabric loader 0.14

**Comment by Shaccoo46** [comment]
Yes i had tried 0.14 fabric loader but that wasn't the greatest idea, most of my mods were not working with it

**Comment by MrMasrozYTLIVE** [comment]
Yeah because there's no point in staying on fabric 0.14 if there's 0.15 which changed some things (Including that one thing that was the reason of this issue. They changed that you don't actually need to pre initialize field with null now)
